# Generated by Django 3.2.8 on 2021-11-28 11:22

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(blank=True, max_length=50, null=True)),
                ('organisasi', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='author/')),
                ('biodata', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, upload_to='event/')),
                ('link_video', models.URLField(blank=True)),
                ('dokumen', models.FileField(blank=True, upload_to='berita/')),
                ('keterangan', models.TextField(blank=True)),
                ('publish', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('mulai', models.DateTimeField()),
                ('selesai', models.DateTimeField(blank=True)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, upload_to='event/')),
                ('link_video', models.URLField(blank=True)),
                ('link_pendaftaran', models.URLField(blank=True)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('isi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskForces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TF', models.CharField(choices=[('0', 'TF1 - Open Trade and Sustainable Investment'), ('1', 'TF2 - Meaningful Digital Connectivity, Cyber Security, Empowerment'), ('2', 'TF3 - Governing Climate Target, Energy Transition and Environmental Protection'), ('3', 'TF4 - Food Security and Sustainable Agriculture'), ('4', 'TF5 - Inequality, Human Capital, and Well-being'), ('5', 'TF6 - Global Health Security and COVID-19'), ('6', 'TF7 - International Finance and Economic Recovery'), ('7', 'TF8 - Resilient Infrastructure and Financing'), ('8', 'TF9 - Global Cooperation for SDGs Financing')], max_length=2)),
                ('policyarea', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cochairs', models.ManyToManyField(to='web.author')),
                ('coordinator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='web.author')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='web.author')),
            ],
        ),
        migrations.CreateModel(
            name='publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='', editable=False, max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.CharField(choices=[('0', 'TF1 - Open Trade and Sustainable Investment'), ('1', 'TF2 - Meaningful Digital Connectivity, Cyber Security, Empowerment'), ('2', 'TF3 - Governing Climate Target, Energy Transition and Environmental Protection'), ('3', 'TF4 - Food Security and Sustainable Agriculture'), ('4', 'TF5 - Inequality, Human Capital, and Well-being'), ('5', 'TF6 - Global Health Security and COVID-19'), ('6', 'TF7 - International Finance and Economic Recovery'), ('7', 'TF8 - Resilient Infrastructure and Financing'), ('8', 'TF9 - Global Cooperation for SDGs Financing')], max_length=2)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, upload_to='event/')),
                ('dokumen', models.FileField(blank=True, upload_to='publications')),
                ('keterangan', models.TextField(blank=True)),
                ('publish', models.BooleanField(default=False)),
                ('author', models.ManyToManyField(to='web.author')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
    ]
