# Generated by Django 3.2.8 on 2021-11-28 15:08

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_event_gambar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AlterField(
            model_name='berita',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='berita'),
        ),
    ]
